//
// asio.hpp
// ~~~~~~~~
//
// Copyright (c) 2003-2023 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//
//  See www.boost.org/libs/asio for documentation.
//

#ifndef BOOST_ASIO_HPP
#define BOOST_ASIO_HPP

#if defined(_MSC_VER) && (_MSC_VER >= 1200)
# pragma once
#endif // defined(_MSC_VER) && (_MSC_VER >= 1200)

#include <b/asio/any_completion_executor.hpp>
#include <b/asio/any_completion_handler.hpp>
#include <b/asio/any_io_executor.hpp>
#include <b/asio/append.hpp>
#include <b/asio/as_tuple.hpp>
#include <b/asio/associated_allocator.hpp>
#include <b/asio/associated_cancellation_slot.hpp>
#include <b/asio/associated_executor.hpp>
#include <b/asio/associated_immediate_executor.hpp>
#include <b/asio/associator.hpp>
#include <b/asio/async_result.hpp>
#include <b/asio/awaitable.hpp>
#include <b/asio/basic_datagram_socket.hpp>
#include <b/asio/basic_deadline_timer.hpp>
#include <b/asio/basic_file.hpp>
#include <b/asio/basic_io_object.hpp>
#include <b/asio/basic_random_access_file.hpp>
#include <b/asio/basic_raw_socket.hpp>
#include <b/asio/basic_readable_pipe.hpp>
#include <b/asio/basic_seq_packet_socket.hpp>
#include <b/asio/basic_serial_port.hpp>
#include <b/asio/basic_signal_set.hpp>
#include <b/asio/basic_socket.hpp>
#include <b/asio/basic_socket_acceptor.hpp>
#include <b/asio/basic_socket_iostream.hpp>
#include <b/asio/basic_socket_streambuf.hpp>
#include <b/asio/basic_stream_file.hpp>
#include <b/asio/basic_stream_socket.hpp>
#include <b/asio/basic_streambuf.hpp>
#include <b/asio/basic_waitable_timer.hpp>
#include <b/asio/basic_writable_pipe.hpp>
#include <b/asio/bind_allocator.hpp>
#include <b/asio/bind_cancellation_slot.hpp>
#include <b/asio/bind_executor.hpp>
#include <b/asio/bind_immediate_executor.hpp>
#include <b/asio/buffer.hpp>
#include <b/asio/buffer_registration.hpp>
#include <b/asio/buffered_read_stream_fwd.hpp>
#include <b/asio/buffered_read_stream.hpp>
#include <b/asio/buffered_stream_fwd.hpp>
#include <b/asio/buffered_stream.hpp>
#include <b/asio/buffered_write_stream_fwd.hpp>
#include <b/asio/buffered_write_stream.hpp>
#include <b/asio/buffers_iterator.hpp>
#include <b/asio/cancellation_signal.hpp>
#include <b/asio/cancellation_state.hpp>
#include <b/asio/cancellation_type.hpp>
#include <b/asio/co_spawn.hpp>
#include <b/asio/completion_condition.hpp>
#include <b/asio/compose.hpp>
#include <b/asio/connect.hpp>
#include <b/asio/connect_pipe.hpp>
#include <b/asio/consign.hpp>
#include <b/asio/coroutine.hpp>
#include <b/asio/deadline_timer.hpp>
#include <b/asio/defer.hpp>
#include <b/asio/deferred.hpp>
#include <b/asio/detached.hpp>
#include <b/asio/dispatch.hpp>
#include <b/asio/error.hpp>
#include <b/asio/execution.hpp>
#include <b/asio/execution/allocator.hpp>
#include <b/asio/execution/any_executor.hpp>
#include <b/asio/execution/blocking.hpp>
#include <b/asio/execution/blocking_adaptation.hpp>
#include <b/asio/execution/context.hpp>
#include <b/asio/execution/context_as.hpp>
#include <b/asio/execution/executor.hpp>
#include <b/asio/execution/invocable_archetype.hpp>
#include <b/asio/execution/mapping.hpp>
#include <b/asio/execution/occupancy.hpp>
#include <b/asio/execution/outstanding_work.hpp>
#include <b/asio/execution/prefer_only.hpp>
#include <b/asio/execution/relationship.hpp>
#include <b/asio/executor.hpp>
#include <b/asio/executor_work_guard.hpp>
#include <b/asio/file_base.hpp>
#include <b/asio/generic/basic_endpoint.hpp>
#include <b/asio/generic/datagram_protocol.hpp>
#include <b/asio/generic/raw_protocol.hpp>
#include <b/asio/generic/seq_packet_protocol.hpp>
#include <b/asio/generic/stream_protocol.hpp>
#include <b/asio/handler_continuation_hook.hpp>
#include <b/asio/high_resolution_timer.hpp>
#include <b/asio/io_context.hpp>
#include <b/asio/io_context_strand.hpp>
#include <b/asio/io_service.hpp>
#include <b/asio/io_service_strand.hpp>
#include <b/asio/ip/address.hpp>
#include <b/asio/ip/address_v4.hpp>
#include <b/asio/ip/address_v4_iterator.hpp>
#include <b/asio/ip/address_v4_range.hpp>
#include <b/asio/ip/address_v6.hpp>
#include <b/asio/ip/address_v6_iterator.hpp>
#include <b/asio/ip/address_v6_range.hpp>
#include <b/asio/ip/network_v4.hpp>
#include <b/asio/ip/network_v6.hpp>
#include <b/asio/ip/bad_address_cast.hpp>
#include <b/asio/ip/basic_endpoint.hpp>
#include <b/asio/ip/basic_resolver.hpp>
#include <b/asio/ip/basic_resolver_entry.hpp>
#include <b/asio/ip/basic_resolver_iterator.hpp>
#include <b/asio/ip/basic_resolver_query.hpp>
#include <b/asio/ip/host_name.hpp>
#include <b/asio/ip/icmp.hpp>
#include <b/asio/ip/multicast.hpp>
#include <b/asio/ip/resolver_base.hpp>
#include <b/asio/ip/resolver_query_base.hpp>
#include <b/asio/ip/tcp.hpp>
#include <b/asio/ip/udp.hpp>
#include <b/asio/ip/unicast.hpp>
#include <b/asio/ip/v6_only.hpp>
#include <b/asio/is_applicable_property.hpp>
#include <b/asio/is_contiguous_iterator.hpp>
#include <b/asio/is_executor.hpp>
#include <b/asio/is_read_buffered.hpp>
#include <b/asio/is_write_buffered.hpp>
#include <b/asio/local/basic_endpoint.hpp>
#include <b/asio/local/connect_pair.hpp>
#include <b/asio/local/datagram_protocol.hpp>
#include <b/asio/local/seq_packet_protocol.hpp>
#include <b/asio/local/stream_protocol.hpp>
#include <b/asio/multiple_exceptions.hpp>
#include <b/asio/packaged_task.hpp>
#include <b/asio/placeholders.hpp>
#include <b/asio/posix/basic_descriptor.hpp>
#include <b/asio/posix/basic_stream_descriptor.hpp>
#include <b/asio/posix/descriptor.hpp>
#include <b/asio/posix/descriptor_base.hpp>
#include <b/asio/posix/stream_descriptor.hpp>
#include <b/asio/post.hpp>
#include <b/asio/prefer.hpp>
#include <b/asio/prepend.hpp>
#include <b/asio/query.hpp>
#include <b/asio/random_access_file.hpp>
#include <b/asio/read.hpp>
#include <b/asio/read_at.hpp>
#include <b/asio/read_until.hpp>
#include <b/asio/readable_pipe.hpp>
#include <b/asio/recycling_allocator.hpp>
#include <b/asio/redirect_error.hpp>
#include <b/asio/registered_buffer.hpp>
#include <b/asio/require.hpp>
#include <b/asio/require_concept.hpp>
#include <b/asio/serial_port.hpp>
#include <b/asio/serial_port_base.hpp>
#include <b/asio/signal_set.hpp>
#include <b/asio/signal_set_base.hpp>
#include <b/asio/socket_base.hpp>
#include <b/asio/static_thread_pool.hpp>
#include <b/asio/steady_timer.hpp>
#include <b/asio/strand.hpp>
#include <b/asio/stream_file.hpp>
#include <b/asio/streambuf.hpp>
#include <b/asio/system_context.hpp>
#include <b/asio/system_executor.hpp>
#include <b/asio/system_timer.hpp>
#include <b/asio/this_coro.hpp>
#include <b/asio/thread_pool.hpp>
#include <b/asio/time_traits.hpp>
#include <b/asio/use_awaitable.hpp>
#include <b/asio/use_future.hpp>
#include <b/asio/uses_executor.hpp>
#include <b/asio/version.hpp>
#include <b/asio/wait_traits.hpp>
#include <b/asio/windows/basic_object_handle.hpp>
#include <b/asio/windows/basic_overlapped_handle.hpp>
#include <b/asio/windows/basic_random_access_handle.hpp>
#include <b/asio/windows/basic_stream_handle.hpp>
#include <b/asio/windows/object_handle.hpp>
#include <b/asio/windows/overlapped_handle.hpp>
#include <b/asio/windows/overlapped_ptr.hpp>
#include <b/asio/windows/random_access_handle.hpp>
#include <b/asio/windows/stream_handle.hpp>
#include <b/asio/writable_pipe.hpp>
#include <b/asio/write.hpp>
#include <b/asio/write_at.hpp>

#endif // BOOST_ASIO_HPP
