# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_encodeSfGeometry <- function(sfc, strip, precision) {
    .Call('_googlePolylines_rcpp_encodeSfGeometry', PACKAGE = 'googlePolylines', sfc, strip, precision)
}

rcpp_encode_polyline <- function(longitude, latitude, precision) {
    .Call('_googlePolylines_rcpp_encode_polyline', PACKAGE = 'googlePolylines', longitude, latitude, precision)
}

polyline_to_wkt <- function(sfencoded) {
    .Call('_googlePolylines_polyline_to_wkt', PACKAGE = 'googlePolylines', sfencoded)
}

wkt_to_polyline <- function(wkt, precision) {
    .Call('_googlePolylines_wkt_to_polyline', PACKAGE = 'googlePolylines', wkt, precision)
}

